### ISSUE TITLE
Linuxbrew: Installed binaries are not executeable

### ISSUE THREAD

**Issue by n-se** [mongodb/homebrew-brew#21]
The installed binaries are not executable by default which results in a `permission denied error`. Other homebrew package binaries are executable.
Environment details: Debian GNU/Linux 9.11 (stretch)
Brew version: 2.1.11-98-g1e584f9 (current latest master)
```
user@pc:~$ mongod
bash: /usr/home/user/.linuxbrew/bin/mongod: Permission denied
```
```
user@pc:~$ ls -la /usr/home/user/.linuxbrew/bin/mongod
lrwxrwxrwx 1 user user 44 Sep 20 09:23 /usr/home/user/.linuxbrew/bin/mongod -> ../Cellar/mongodb-community/4.2.0/bin/mongod
```
```
user@pc:~/.linuxbrew/Cellar/mongodb-community/4.2.0/bin$ ls -la
total 278884
drwxr-xr-x 2 user user     4096 Sep 20 09:23 .
drwxr-xr-x 4 user user     4096 Sep 20 09:23 ..
-r--r--r-- 1 user user 10007288 Aug  9 07:04 bsondump
-r-xr-xr-x 1 user user     7700 Aug  9 07:40 install_compass
-r--r--r-- 1 user user 46967016 Aug  9 07:17 mongo
-r--r--r-- 1 user user 72172612 Aug  9 07:40 mongod
-r--r--r-- 1 user user 14524964 Aug  9 07:04 mongodump
-r--r--r-- 1 user user 14273316 Aug  9 07:04 mongoexport
-r--r--r-- 1 user user 14230012 Aug  9 07:04 mongofiles
-r--r--r-- 1 user user 14445468 Aug  9 07:04 mongoimport
-r--r--r-- 1 user user 17626204 Aug  9 07:04 mongoreplay
-r--r--r-- 1 user user 14839772 Aug  9 07:04 mongorestore
-r--r--r-- 1 user user 38379304 Aug  9 07:26 mongos
-r--r--r-- 1 user user 14019372 Aug  9 07:04 mongostat
-r--r--r-- 1 user user 13690636 Aug  9 07:04 mongotop
```

**Comment by chasinglogic** [comment]
We're discussing this internally. We haven't considered supporting linuxbrew up to this point. The problem with simply adding "chmod 0755" or some other equivalent in the Formula is that what you have downloaded there are MacOS binaries and so would not work even if they were executable.

We no longer build generic Linux binaries due to problems with openssl and so would effectively require that all users of Linuxbrew would have to compile MongoDB every time they upgraded (including minor versions) or installed it.

As a stop gap while we discuss this, if you're on a supported linux distribution, we provide repositories that have every supported version of mongodb available in your distributions preferred package manager / format.

**Comment by n-se** [comment]
You probably do not use Linuxbrew if you have root access. Linuxbrew more interesting for things like webhosting with SSH access or on a linux terminal server.

**Comment by n-se** [comment]
Any updates on this?

**Comment by chasinglogic** [comment]
@n-se This isn't a priority for us at this moment. We aren't opposed to supporting Linuxbrew but we don't currently have the resources to dedicate to making it.

If you would like to implement the support and submit a PR we'd be happy to review it.

**Comment by ekremkaraca** [comment]
I have same issue here. With recent update of linuxbrew, mongodb formulae was removed. If I give permission to mongod with:

```shell
# echo $LINUXBREW_HOME returns /home/linuxbrew/.linuxbrew
chmod +x $LINUXBREW_HOME/Cellar/mongodb-community/4.2.1/bin/mongod
```

then I got another error like below:

```shell
❯ mongod --config /home/linuxbrew/.linuxbrew/etc/mongod.conf        
zsh: exec format error: mongod
```

It seems it's time to make it fixed soon.

**Comment by chasinglogic** [comment]
We're disable Github Issues on this repository and directing users to our normal support channels. I've moved this ticket to JIRA and scheduled it for Triage today.

Moved to https://jira.mongodb.org/browse/SERVER-45021
